version: '3.8'

services:
  pseudorandom-api:
    container_name: pseudorandom-api
    image: pseudorandom-api:latest
    ports:
      - "8081:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - monitoring_net
    labels:
      logging_jobname: "apis"
      logging: "promtail"

networks:
  monitoring_net:
    external:
      name: monitoring